### ISSUE TITLE
vim-news-headlines?

### ISSUE THREAD

**Issue by shaggyaxe** [skamsie/news#1]
RE: https://github.com/skamsie/vim-news-headlines

Do you have plans on bringing back vim-news-headlines?
I thought it was pretty cool.

Thanks

**Comment by skamsie** [comment]
I have a new repo https://github.com/skamsie/nnn which is pretty much the same thing, you just have to replace the old vars with `nnn...`. I am glad you like it :)

For example `g:nnn_wrap_text` instead of `vim_news_headlines_wrap_text`.

**Comment by shaggyaxe** [comment]
Cool, I'll switch over to using that.

Thanks!
